### PR TITLE
adding githubworkflows and go mod file to the project

### PR DESCRIPTION
**Pull request by munishsuri**
Changes Made:

1. Removed Travis CI
2. Added GithubWorkflow for CI
3. Added Go Mod File for Newer Go Version

### CODE REVIEW

**Comment by shamsher31** [comment]
Thanks for your PR @munishsuri .

Can you please also run `go mod tidy` and commit changes if any?
Ref: https://stackoverflow.com/questions/71495619/difference-between-go-mod-download-and-go-mod-tidy

**Comment by munishsuri** [comment]
@shamsher31  - thanks for the review, go mod tidy does not have any changes, just some spaces - which could be my editor.

**Review by shamsher31 — APPROVED** [review]

**Comment by shamsher31** [comment]
@munishsuri Looks like `go.sum` file is missing and the warning is thrown in the build.
https://github.com/shamsher31/goip/actions/runs/6170774258

It's an opportunity for you to raise another PR and fix it.

**Comment by munishsuri** [comment]
Hi @shamsher31 , many thanks for the input, this repo does not have dependency to any other repo, hence go.sum would be empty , I am abstaining from adding additional empty files.
Still let me know your thoughts, we can go from there.

**Pull request merged**
